### ISSUE TITLE
Offer caching for HTTP

### ISSUE THREAD

**Issue by h4cc** [Baachi/CouchDB#22]
There is a Guzzle middleware for caching via ETag and such. That could be integrated and offered by this client:

https://github.com/Kevinrob/guzzle-cache-middleware/issues/8#issuecomment-119225533

**Comment by Baachi** [comment]
Why not use the offical plugin? https://github.com/guzzle/cache-subscriber
Don't know if it belongs to the core of this library.

**Comment by h4cc** [comment]
Because of reasons:

The official is (not yet) Guzzle 6 ready: https://github.com/guzzle/cache-subscriber/issues/63

**Comment by Baachi** [comment]
Then it would be better to send a PR to the cache-subscriber repo to make it compatible. 
This is how open source works :sparkles:
